package com.moods.bikersrides.database.dao;

import android.database.sqlite.SQLiteDatabase;

import com.moods.bikersrides.database.vao.Ride;
import com.moods.bikersrides.database.vao.RideImage;
import com.moods.bikersrides.database.vao.Via;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rideImageDaoConfig;
    private final DaoConfig viaDaoConfig;
    private final DaoConfig rideDaoConfig;

    private final RideImageDao rideImageDao;
    private final ViaDao viaDao;
    private final RideDao rideDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rideImageDaoConfig = daoConfigMap.get(RideImageDao.class).clone();
        rideImageDaoConfig.initIdentityScope(type);

        viaDaoConfig = daoConfigMap.get(ViaDao.class).clone();
        viaDaoConfig.initIdentityScope(type);

        rideDaoConfig = daoConfigMap.get(RideDao.class).clone();
        rideDaoConfig.initIdentityScope(type);

        rideImageDao = new RideImageDao(rideImageDaoConfig, this);
        viaDao = new ViaDao(viaDaoConfig, this);
        rideDao = new RideDao(rideDaoConfig, this);

        registerDao(RideImage.class, rideImageDao);
        registerDao(Via.class, viaDao);
        registerDao(Ride.class, rideDao);
    }
    
    public void clear() {
        rideImageDaoConfig.getIdentityScope().clear();
        viaDaoConfig.getIdentityScope().clear();
        rideDaoConfig.getIdentityScope().clear();
    }

    public RideImageDao getRideImageDao() {
        return rideImageDao;
    }

    public ViaDao getViaDao() {
        return viaDao;
    }

    public RideDao getRideDao() {
        return rideDao;
    }

}
