package com.moods.bikersrides.database.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.moods.bikersrides.database.vao.RideImage;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RIDE_IMAGE.
*/
public class RideImageDao extends AbstractDao<RideImage, Long> {

    public static final String TABLENAME = "RIDE_IMAGE";

    /**
     * Properties of entity RideImage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ImgPath = new Property(1, String.class, "imgPath", false, "IMG_PATH");
        public final static Property RideId = new Property(2, Long.class, "rideId", false, "RIDE_ID");
    };

    private Query<RideImage> ride_ImagesQuery;

    public RideImageDao(DaoConfig config) {
        super(config);
    }
    
    public RideImageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'RIDE_IMAGE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'IMG_PATH' TEXT," + // 1: imgPath
                "'RIDE_ID' INTEGER);"); // 2: rideId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RIDE_IMAGE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RideImage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String imgPath = entity.getImgPath();
        if (imgPath != null) {
            stmt.bindString(2, imgPath);
        }
 
        Long rideId = entity.getRideId();
        if (rideId != null) {
            stmt.bindLong(3, rideId);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RideImage readEntity(Cursor cursor, int offset) {
        RideImage entity = new RideImage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // imgPath
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // rideId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RideImage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImgPath(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRideId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RideImage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RideImage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "images" to-many relationship of Ride. */
    public List<RideImage> _queryRide_Images(Long rideId) {
        synchronized (this) {
            if (ride_ImagesQuery == null) {
                QueryBuilder<RideImage> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RideId.eq(null));
                ride_ImagesQuery = queryBuilder.build();
            }
        }
        Query<RideImage> query = ride_ImagesQuery.forCurrentThread();
        query.setParameter(0, rideId);
        return query.list();
    }

}
