package com.moods.bikersrides.database.vao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RIDE_IMAGE.
 */
public class RideImage {

    private Long id;
    private String imgPath;
    private Long rideId;

    public RideImage() {
    }

    public RideImage(Long id) {
        this.id = id;
    }

    public RideImage(Long id, String imgPath, Long rideId) {
        this.id = id;
        this.imgPath = imgPath;
        this.rideId = rideId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    public Long getRideId() {
        return rideId;
    }

    public void setRideId(Long rideId) {
        this.rideId = rideId;
    }

}
