package com.moods.bikersrides.database.vao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VIA.
 */
public class Via {

    private Long id;
    private String via;
    private Long rideId;

    public Via() {
    }

    public Via(Long id) {
        this.id = id;
    }

    public Via(Long id, String via, Long rideId) {
        this.id = id;
        this.via = via;
        this.rideId = rideId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getVia() {
        return via;
    }

    public void setVia(String via) {
        this.via = via;
    }

    public Long getRideId() {
        return rideId;
    }

    public void setRideId(Long rideId) {
        this.rideId = rideId;
    }

    @Override
    public String toString() {
        return via;
    }
}
